### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by GenevieveKrause** [NCBI-Codeathons/psss-team3-hard-annotation#1]
![image](https://user-images.githubusercontent.com/25143308/134733267-3e207564-2626-443d-8bd8-a544dafb8607.png)
![image](https://user-images.githubusercontent.com/25143308/134734325-73e22ef3-481e-4d0f-82bd-9d4f096ac5dc.png)
![image](https://user-images.githubusercontent.com/25143308/134738374-08a74f8b-4ca5-4a9c-aad0-78198522ee32.png)

**Comment by traviswheeler** [comment]
I believe this issue was created while testing file upload, and should no longer be open.  So I'm closing it. Change that, if I'm wrong.
